### ISSUE TITLE
Heading Styles

### ISSUE THREAD

**Issue by jordanwillis** [bree1106/prj-rev-bwfs-dasmoto#2]
I noticed that your `<h2>` headings did not include their respective background colors as displayed on the project specification. 

https://rawgit.com/bree1106/prj-rev-bwfs-dasmoto/master/Dasmoto/index.html

It looks like the reason for this has to do with your CSS selectors shown below.

https://github.com/bree1106/prj-rev-bwfs-dasmoto/blob/ea5aadb1a1cb6987321d8a0e373cc965154523e5/Dasmoto/resources/index.css#L15-L23

Don't forget that text within a selector that does not include a period or hashtag must refer to valid HTML elements only.  In this case, `brushes`, `frames`, and `paint` or not HTML elements.  Secondly, also remember that the order of your selector components matter.  If you were trying to target each `<h2>` within each component, then you would need to reverse the order like this.

``` css
.brushes h2 {

}
```

Notice also that I have added a period because `brushes` refers to a class name.

If you have taken a look at my HTML Sturcture feedback and noticed my recommendation to use the same class name for each component (e.g. `item`).  Then all you need to do is give each `<h2>` element a specific ID, and your final CSS would look like this.

``` css
.item h2 {
  font-size: 32px;
  color: white;
}

#brush {
  background-color: mediumspringgreen;
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```
