### ISSUE TITLE
DRY CSS

### ISSUE THREAD

**Issue by jordanwillis** [bree1106/prj-rev-bwfs-dasmoto#4]
Your CSS looks pretty good but one way to ensure you are writing great CSS is to apply the DRY (don't repeat yourself) principle.  This is an extremely important principle in software engineering that has to do with preventing duplicate code.  In the case of CSS, duplicate code is the same as duplicate properties.  So the idea is to ensure that we aren't using the same properties and style values across multiple selectors.  This results in code that is easier to maintain and extend in the future.

In your CSS, the main duplication that I see if with your font related properties.  Some ways that we can prevent the duplication is to either set the property in a broad selector that will be inherited by others or by creating combo selectors that apply the same property to many selectors as the same time (which is what I am showing below).

``` css
h1, 
h2, 
h3, 
p {
  font-family: "Helvetica", sans-serif;
}

h1 {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align: center;
  font-size: 100px;
  color: khaki;
}

.item h2 {
  font-size: 32px;
  color: white;
}

.price {
  font-weight: bold;
  color: blue;
}

#brush {
  background-color: mediumspringgreen;
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```
